<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="WIN-NQS2KO6930I" failures="1" tests="5" name="Test" time="77.573" errors="0" timestamp="2023-09-23T17:28:09 IST">
  <testcase classname="tests.FourTest" name="testfour" time="0.013"/>
  <testcase classname="tests.TwoTest" name="testtwo" time="0.002"/>
  <testcase classname="tests.ThreeTest" name="testthree" time="0.005"/>
  <testcase classname="tests.LoginTest" name="login" time="16.201">
    <failure type="java.lang.AssertionError" message="expected [Success] but found [Failure]">
      <![CDATA[java.lang.AssertionError: expected [Success] but found [Failure]
at tests.LoginTest.login(LoginTest.java:58)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- login -->
  <testcase classname="tests.LoginTest" name="login" time="16.404"/>
</testsuite> <!-- Test -->
